name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: ./scripts/buildprod.sh

      - name: Set up GCloud auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up GCloud
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Set up goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Upload image to GCR
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/notely-413322/notely-ar-repo/jerrydevs/notely:latest .

      - name: Run DB migrations
        run: ./scripts/migrateup.sh

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-413322/notely-ar-repo/jerrydevs/notely:latest --region us-central1 --allow-unauthenticated --max-instances=4 --project notely-413322
